"""init2

Revision ID: e7538900b5e7
Revises: 6ba3799567d2
Create Date: 2023-05-09 11:27:16.593050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7538900b5e7'
down_revision = '6ba3799567d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
